buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 1.19-hubspot

provides: [com.sun.jersey:jersey-core]
