buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 1.19-hubspot

depends: [com.sun.jersey:jersey-core, com.sun.jersey:jersey-server]
